[features]
seeds = false
skip-lint = false

[programs.localnet]
calculator = "72tyNt2vq4ySQsBS5GXxiPhJh3pSEE68FNcrm3vasxKf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/irenefabris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"